name: infra-dev

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "infra/**"

permissions:
  contents: read
  id-token: write

env:
  BICEP_FILE: infra/bicep/main.bicep
  BICEP_PARAMS: infra/bicep/params/dev.bicepparam

jobs:
  deploy_infra_dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate infra (bicep)
        run: >
          az deployment group validate
          --resource-group "${{ secrets.AZURE_RG_DEV }}"
          --template-file "${{ env.BICEP_FILE }}"
          --parameters @"${{ env.BICEP_PARAMS }}"
          --parameters sqlAdminPassword="${{ secrets.SQL_ADMIN_PASSWORD_DEV }}"

      - name: Deploy infra (bicep)
        run: >
          az deployment group create
          --resource-group "${{ secrets.AZURE_RG_DEV }}"
          --template-file "${{ env.BICEP_FILE }}"
          --parameters @"${{ env.BICEP_PARAMS }}"
          --parameters sqlAdminPassword="${{ secrets.SQL_ADMIN_PASSWORD_DEV }}"
